---
title: "Protocol: Substituting  meat, poultry, and fish with legumes and risk of gallbladder diseases in a large prospective cohort"
# Add all *direct* contributors to the protocol here
author:
  - name: Fie Langmann
    orcid: "0000-0003-3474-9346"
    roles:
      - "writing – original draft"
      - "formal analysis"
      - "investigation"
      - "conceptualization"
    affiliations:
      - name: Aarhus University
  - name: Daniel Borch Ibsen
    orcid: "0000-0002-7038-4770"
    roles:
      - "supervision"
      - "project administration"
      - "writing – review & editing"
      - "conceptualization"
    affiliations:
      - name: Aarhus University
      - name: Steno Diabetes Center Aarhus
  - name: Luke W. Johnston
    orcid: "0000-0003-4169-2616"
    roles:
      - "software"
      - "project administration"
      - "writing – review & editing"
      - "data curation"
      - "resources"
    affiliations:
      - name: Aarhus University
      - name: Steno Diabetes Center Aarhus
  - name: Christina Catherine Dahm
    orcid: "0000-0003-0481-2893"
    roles:
      - "supervision"
      - "project administration"
      - "writing – review & editing"
      - "conceptualization"
    affiliations:
      - name: Aarhus University
date: May 29, 2024
format: html
embed-resources: true
bibliography: gbd.bib
# You can browse all the Citation Styles here: https://github.com/citation-style-language/styles
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/vancouver.csl
execute:
  echo: true
editor:
  markdown:
    wrap: 72
---

```{r setup}
#| include: false
# Include packages here if needed.
```

::: content-hidden
This is a template for writing your protocol in a format that based on
features used in the [Open Science Framework registry](https://osf.io/)
for all types of studies. Because this database is not for observational
studies per se, there are fields that are not relevant for you to fill
in. These fields have not been included in this template. Also, all
fields where you have to check a list of items or similar, have also
been excluded from this template.

Please also refer to a relevant reporting checklist (e.g. STROBE) when
describing the study. Find checklists
[here](https://www.equator-network.org/).
:::

# Study information

## Substituting meat, poultry, and fish with legumes and risk of gallbladder diseases in a large prospective cohort

## Description

Western diets high in animal foods and saturated fats has been shown to
cause a multitude of non-communicable diseases while also having great
and negative impacts on the environment. Based on a combined
environmental and health related focus, legumes are increasingly being
recommended as a meat substitute. Previous research has however
indicated an increased risk of developing gallbladder related diseases
when consuming large amounts of legumes and this study therefore
investigates the association between substituting legumes for meats,
poultry, and fish and the risk of developing gallbladder diseases.

`r ukbAid::statements$protocol`

## Objectives and hypotheses

### Background
The EAT-Lancet reference diet was introduced in 2019 as a globally
sustainable and healthy diet emphasizing plant-based proteins instead of
animal-based proteins, e.g., with a recommendation of 100 g legumes
daily [@Springmann2020; @Willett2019].

Consumption of pulse-rich diets has been associated with overall better diet quality and greater health [@Mitchell2009; @Papanikolaou2008]. However, pulses contain a range of bioactive compounds, which may increase the biliary cholesterol secretion. This may consequently have implications for the risk of gallstone development and related comorbidities [@Chavez2014; @Li2013; @Li2019].

As legumes are a source of both carbohydrates and proteins, research frequently compares legumes with
other carbohydrate sources [@Sievenpiper2009; @Jayalath2014;
@Belski2011; @Linlawan2019; @Lee2008]. Observed associations for foods
may be due to the specific foods themselves. However, the associations
could also represent the effect of the dietary pattern in which the
specific food is consumed. When individuals limit intake of certain food
groups, they will most often increase the intake of certain other food
groups, in an otherwise stable diet [@Ibsen2020; @Ibsen2022]. The
association of such food intake will not only be caused by the increased
consumption of one food, but rather the substitution effect including
various foods.


Consumption of legumes in Western countries has been negligible to date
and the impact of markedly increasing intakes of legumes on
gallbladder diseases is understudied. Therefore, this study aims to investigate the association between replacing red and processed meat, poultry, or fish with pulses and the risk of gallbladder diseases (gallstone, inflammation of the gallbladder, and removal of the gallbladder) contingent on potential confounders of the associations. As it might be more feasible for Western populations to include pulses and substituting dietary components that are not animal-based, this study also aimed to investigate the association between non-specific substitution of any other food groups for pulses and the risk of gallbladder diseases.

**Hypothesis**

-   Replacing meats intake with legumes is associated with
    an increased risk of gallbladder diseases.

-   Replacing poultry or fish intakes with legumes is not associated with the risk
    of gallbladder diseases.

-   Replacing non-specific foods with legumes is not associated with
    gallbladder diseases.


# Design plan

## Study type

**Observational Study**. Data is collected from study subjects that are
not randomly assigned to a treatment. This includes surveys, natural
experiments, and regression discontinuity designs.

## Blinding

No blinding is involved in this study.

## Study design

**Study population and setting**

The initial recruitment of participants for the UK Biobank started in
2006 and ran until June 2010. Of 9.2 million people identified from the
National Health Service registers and invited to participate in the
study, 5.5% participated, approximately 500,000 participants, aged 37-73
years at baseline. The study protocol and more information are available
elsewhere [@Sudlow2015; @Biobank2007]. All participants gave written,
informed consent before baseline, and the study was approved by the
National Information Governance Board for Health and Social Care and the
National Health Service North West Multicentre Research Ethics Committee
(reference number 06/MRE08/65).

# Sampling plan

## Existing data

**Registration prior to analysis of the data**. As of the date of
submission, the data exist and you have accessed it, though no analysis
has been conducted related to the research plan (including calculation
of summary statistics). A common situation for this scenario when a
large dataset exists that is used for many different studies over time,
or when a data set is randomly split into a sample for exploratory
analyses, and the other section of data is reserved for later
confirmatory data analysis.

## Explanation of existing data

The UK Biobank is a large national cohort of participants in the UK,
with data collected in a standardized format the the sole purpose of
providing a data resource for researchers to use for health research.
All information about collection procedures, limitations, and sources of
bias are well established and described by the UK Biobank resource.

Because of its size of data collected, it is near impossible to a priori
see patterns in the data that might influence how the analysis will be
conducted, unless specifically looked for or previously published on. In
this way, we feel pre-analysis bias is minimal.

## Data collection procedures

**Study population and setting**

At baseline, participants provided detailed information on several
sociodemographic, physical, lifestyle, and health-related
characteristics via self-completed touch-screen questionnaires and a
computer assisted personal interview [@Fry2017]. Professionally trained
staff did physical, anthropometric, and biomedical measures following
standardized procedures [@Sudlow2015]. Diet was assessed through a
touchscreen questionnaire at baseline and a 24-hour dietary assessment
tool (Oxford WebQ) designed for the UK Biobank study. The 24-hour
dietary assessment tool was completed by participants up to five times
and 210,965 individuals completed one or more 24-hour dietary
assessments [@Biobank2021].

**Assessment of diet**

The Oxford WebQ was designed as an internet based 24-hour dietary
assessment tool for measuring diet on repeated occasions. The
questionnaire is a short set of food frequency questions on commonly
eaten food groups in the British population on the day before. The
questionnaire aims to measure the type and quantity of food and
beverages consumed in the last 24 hours and estimate nutrients from the
entered information through the UK Nutrient Databank Food Composition
Tables [@Liu2011; @PerezCornago2021]. The Oxford WebQ was compared with
interviewer-administered 24-hour dietary recalls and validated for macro
nutrients and total energy intake using recovery biomarkers and compared
with a single food frequency questionnaire [@Liu2011; @Greenwood2019;
@Carter2019]. Recently, the Oxford WebQ nutrient calculation was updated
to provide more detailed information on nutrient intakes and to
incorporate new dietary variables [@PerezCornago2021]. Participants
recruited between April 2009 and September 2010 completed the Oxford
WebQ at baseline (n=70,747). The Oxford WebQ was not available until
April 2009 and participants recruited before that date who provided a
valid email address were invited to complete the four subsequent 24-hour
dietary assessments online [@Kelly2021].

**Legumes**

Legume consumption will be estimated based on participants' reported
diets from the self-administered online 24-hour dietary assessments, the
Oxford WebQ. Consumption of legumes and pulses will be based on total
weight by food group intakes estimated from participants' responses in
the Oxford WebQ. Despite the high detail level of the Oxford WebQ, a
single 24-hour dietary assessment cannot capture habitual intake of
legumes in a UK setting [@FAO2018]. Therefore, this study will include
varying numbers of 24-hour dietary assessments to ensure that we capture
the usual intake of legumes. Usual intake will be estimated as a daily
average across available 24-hour dietary assessments.

**Meat, poultry, and fish**

Consumption of red and processed meats, poultry, and fish will be based
on total weight by food group intakes estimated from participants'
responses to the Oxford WebQs. Red and processed meat will be defined as
beef, pork, lamb, and other meats including offal, and processed meat
including sausages, bacon, ham, and liver paté. Poultry will be defined
as poultry with or without skin, and fried poultry with batter or
breadcrumbs. Fish will be defined as oily fish, white fish and tinned
tuna, fried fish with batter or breadcrumbs, and shellfish.

**Gallbladder diseases**
Incident cases of gallbladder diseases includes incident cholelithiasis, cholecystitis, and cholecystectomy assessed through linkage to the National Health Service registers. Diagnosis after hospital admission or primary care visits were coded according to the International Classification of Diseases and Related Health Problems 10th edition disease codes (ICD-10) or operative procedure codes (OPCS) [@NHSICD; @NHSOPCS; @Biobank2020].
Cholecystitis and cholelithiasis can occur more than once, but only the first and incident diagnosis was included as an outcome. Diagnosis can only provide information on presence of inflammation or gallstone but no information on whether the patient recovers completely. Further, individuals can have undiagnosed gallstones with no symptoms, while previous incidence of symptomatic cholelithiasis or cholecystitis is associated with a higher risk of developing symptoms in the future. Individuals do not necessarily develop new gallstones, but experience symptoms due to the gallstones already present in the gallbladder (82). Date of first diagnosis will be used as the precise measure of each outcome. Incident cases of cholelithiasis were diagnosed with ICD- 10-codes K80.0-K80.8 at first admission to the hospital or through OPCS-4  codes J21.1, J24.2-3, J26.1, J33.1-J33.2, J41.1, J41.3, J49.1, J49.2, and J52.1. Incident cases of cholecystitis were diagnosed with ICD-10-codes K81.0-K81.9. Incident cases of cholecystectomy were diagnosed with OPCS-4 codes J18.1-3 and J18.8-9 [@NHSICD; @NHSOPCS; @Biobank2020].

**Covariates**
Directed acyclic graphs were used to illustrate the potential and known
association between covariates of the association between substituting
meat, poultry or fish for legumes and development of gallbladder disease.
Information on covariates will include information on all other dietary
components based on total weight by food group intakes as g/week
retrieved from the Oxford WebQ (fruits, vegetables, cereal products,
dairy products, egg products, nuts, mixed dishes, condiments, added
sugar and sweets, non-alcoholic beverages, and alcoholic beverages), sex
(male, female), age (years), alcohol consumption (g ethanol/day), ethnic
group (white, mixed or other, Asian, black), socioeconomic status
(Townsend deprivation score, educational level),
geographical region of recruitment (ten UK regions), cohabitation
(alone, with spouse/partner, with other non-partner, no answer),
anthropometry (BMI \[kg/m2\]), physical activity (low \[≤918
MET-min/week\], moderate \[918-3706 MET-min/week\], high \[≥3706
MET-min/week\], and unknown) [@Cassidy2016], smoking status (never, former, current 1-15 cigarettes per day, current ≥15 cigarettes per day, unknown), rapid  weight loss (yes, no), history of gallbladder related conditions (participants’ diagnosis of diabetes, elevated cholesterol, use of hormone replacement therapy  drugs for women [yes, no], used of oral contraceptives  for women [yes, no]), and family history of gallbladder related conditions (diabetes, elevated cholesterol, gallbladder disease). Blood samples were drawn at baseline for all participants to measure total bilirubin  levels as there has been found a causal association between elevated total bilirubin and risk of gallbladder diseases [@Sun2023].  

## Sample size

For this cohort study, only participants with two or more 24 h dietary
assessments and complete information on covariates will be included in
the analyses.

## Sample size rationale

# Variables

## Measures variables

**Exposures:** g/week consumption of legumes, meats, poultry, and fish

**Outcomes:** gallstone, gallbladder inflammation, gallbladder removal

**Covariates:** g/week consumption of fruits, vegetables, cereal
products, dairy products, egg products, nuts, mixed dishes, condiments,
added sugar and sweets, non-alcoholic beverages, and alcoholic
beverages. Sex, age, ethnic group, Townsend deprivation score,
educational level, geographical region of recruitment (ten UK regions),
cohabitation, obesity, physical activity, smoking status, rapid weight loss, own and family
history of gallbladder related conditions.


# Analysis plan

## Statistical models (UPDATE)

### Main analyses

Standard summary statistics will be performed to describe the
distribution of baseline characteristics and food consumption as an
average g/week based on participants' 24-h WebQ responses. Multi-variable
adjusted Cox Proportional Hazards regression models will be used to
estimate the hazard ratios for gallbladder disease based on replacing meats, poultry,
or fish with legumes.

-   Replacing red and processed meats, poultry, or fish with legumes
    (e.g., per 80 g/week)

Age will be used as the underlying time scale in the analyses. Person-years at risk were calculated from the date of last completed Oxford WebQ to the date of death, loss to follow-up, diagnosis of gallbladder disease , or right censoring, whichever occurred first. As participants in UKB are still followed-up today, participants will be
right censored at the date of the most recent registry update of full
follow-up for the outcomes. The substitution analyses will be
conducted with different adjustment levels.

**Model 1** will be stratified for age (<45, 45-49, 50-54, 55-59, 60-64, ≤65 years) at recruitment and geographical region of recruitment (ten UK regions), and adjusted for sex, and intake of all other dietary components apart from the two substitutes. When substituting g legumes/week, the unit for all dietary components will be g/week and the total weekly intake of all foods will be held stable in the analysis

**Model 2** will be further adjusted for ethnic group (white, mixed background, Asian, black, other, and unknown), socioeconomic status (Townsend deprivation score, educational level, yearly income), cohabitation (alone, with spouse or partner, with non-partner, unknown), physical activity (low [≤ 918 METs/week], moderate [≥918 – 3706 METs/week], high [≤37069 METs/week], and unknown), smoking status (never, former, current 1-15 cigarettes per day, current ≥15 cigarettes per day, unknown), rapid  weight loss (yes, no), history of gallbladder related conditions (yes, no), and family history of gallbladder related conditions (yes, no).

**Model 3** will be further adjusted for anthropometry (BMI ≥ 30 kg/m2), as
obesity may either confound or mediate the association between replacing
red and processed meats, poultry, or fish with legumes and risk of gallbladder disease.

### Secondary and sensitivity analyses

To evaluate the association between overall legume intake and gallbladder disease
risk, hazard ratios associated with a 80 g/week increase in legumes will
be estimated following adjustment levels in model 2. Secondary analyses will also include a non-specific substitution of legumes and pulses for any other food component to evaluate the association with gallbladder diseases. Adjustment will follow model 2.  

Peas are increasingly used as a plant-based meat alternative in the food
industry [@Maningat2022]. Despite this, peas are also included in the
NHS 5 A Day recommendations for fruit and vegetables consumption in the
UK [@Services2022]. Therefore, in secondary analyses consumption of
legumes will include participants self-reported intake of legumes and
pulses together with consumed peas. The amount of peas consumed will be
estimated based on participants' reported daily portions consumed with a
portion size of peas weighing 80 g [@Services2021].

To evaluate the robustness of the main analyses, sensitivity analyses
will include varying numbers of Oxford WebQ returns, and removal of
participants in the highest 90th percentile of total bilirubin levels. 

All analyses will be conducted in R with a significance level of 5%.


## Transformations


## Inference criteria

All analyses will be evaluated based on two-sided p-values. Values below
5% are classified as statistically significant. Inference on relevance
and significance and the evaluation of, whether a result is meaningful
will be based on the size of the estimate, and confidence intervals
containing 1 or 0, for ratios or absolute measures respectively.

## Data exclusion

**Exclusion criteria**
Only participants with two or more completed Oxford WebQs are eligible for analyses. Participants who had their gallbladder removed or were diagnosed with cholelithiasis or cholecystitis before the last completed Oxford WebQ will be excluded from analyses.   


## Missing data
Missing data on covariates at baseline will also be a cause for exclusion of participants. 


# Other

# References
